Repository redBorder/redborder-rubyrvm, pull requests merged in 2024-07, with the labels that each got.

#26 Feature/incident response
  packaging/rpm/Gemfile_web
Labels: size/XS, kind/feature

#25 SSO SAML gem added
  .github/workflows/rpm.yml
  packaging/rpm/Gemfile_web
  packaging/rpm/Makefile
  packaging/rpm/download_makerpm_gems.sh
Labels: kind/documentation, size/XS

#28 Release 0.5.0
  VERSION
  packaging/rpm/Gemfile_web
Labels: kind/documentation, size/M
